version: v0.2.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        run_id:
          display:
            description: Optional string identifier for this workflow run
            name: Run ID
          type:
            type_id: string
          default: '"none"'
          required: false
        kubeconfig:
          display:
            description: The complete kubeconfig file as a string
            name: Kubeconfig file contents
          type:
            type_id: string
          required: true
        k8s_namespace:
          display:
            description: The kubernetes namespace to host the containers
            name: Kubernetes namespace
          type:
            type_id: string
          default: '"default"'
          required: false
        pcp_pmlogger_interval:
          display:
            description: The logger collection interval for PCP pmlogger
            name: PCP pmlogger collection interval
          type:
            type_id: float
        stressng_params:
          type:
             type_id: ref
             id: StressNGParams
             namespace: $.steps.stressng.starting.inputs.input
          required: true

steps:
  uuidgen:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-utilities:0.5.1
    step: uuid
    input: {}
  kubeconfig:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-kubeconfig:0.3.1
    input:
      kubeconfig: !expr $.input.kubeconfig
  pcp:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-pcp:0.8.0
    step: start-pcp
    input:
      pmlogger_interval: !expr $.input.pcp_pmlogger_interval
    stop_if: !expr $.steps.stressng.outputs
    deploy:
      deployer_name: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        metadata:
          namespace: !expr $.input.k8s_namespace
          labels:
            arcaflow: pcp
        spec:
          pluginContainer:
            imagePullPolicy: IfNotPresent
  stressng:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-stressng:0.8.1
    step: workload
    input: !expr $.input.stressng_params
    wait_for: !expr $.steps.pcp.starting.started
    deploy:
      deployer_name: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        metadata:
          namespace: !expr $.input.k8s_namespace
          labels:
            arcaflow: stressng
        spec:
          pluginContainer:
            imagePullPolicy: IfNotPresent
  metadata:
    plugin:
      deployment_type: image
      src: quay.io/arcalot/arcaflow-plugin-metadata:0.4.0
    input: {}
    deploy:
      deployer_name: kubernetes
      connection: !expr $.steps.kubeconfig.outputs.success.connection
      pod:
        metadata:
          namespace: !expr $.input.k8s_namespace
          labels:
            arcaflow: metadata
        spec:
          pluginContainer:
            imagePullPolicy: IfNotPresent

outputs:
 success:
  uuid: !expr $.steps.uuidgen.outputs.success.uuid
  run_id: !expr $.input.run_id
  pcp: !expr $.steps.pcp.outputs.success
  stressng: !expr $.steps.stressng.outputs.success
  metadata: !expr $.steps.metadata.outputs.success
