input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        kubeconfig:
          display:
            description: The complete kubeconfig file as a string
            name: Kubeconfig file contents
          type:
            type_id: string
steps:
  read_kubeconfig:
    plugin: quay.io/arcalot/arcaflow-plugin-kubeconfig:latest
    input:
      kubeconfig: !expr $.input.kubeconfig
  create_service:
    plugin: quay.io/arcalot/arcaflow-plugin-service:latest
    deploy:
      type: podman
      podman:
        networkMode: host
    input:
      connection: !expr $.steps.read_kubeconfig.outputs.success.connection
      service:
        metadata:
          namespace: default
          # Service metadata here
        spec:
          ports:
           - name: workload
             port: 50000
             protocol: TCP

output:
  test: "test"
