input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        nickname:
          display:
            description: Just a name
            name: Name
          required: true
          type:
            type_id: string

steps:
  metadata:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
    input: {}
  example:
    plugin: quay.io/arcalot/arcaflow-plugin-example:0.2.0
    input:
      name:
        _type: nickname
        nick: !expr $.input.nickname
    wait_for: !expr $.steps.metadata.outputs.success

outputs:
 success:
   metadata: !expr $.steps.metadata.outputs.success
   example: !expr $.steps.example.outputs.success
