input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        pmlogger_interval:
          display:
            description: The logger collection interval for PCP pmlogger
            name: PCP pmlogger collection interval
          type:
            type_id: integer
        sysbench_threads:
          display:
            description: The number of threads sysbench will run
            name: sysbench threads
          type:
            type_id: integer
        sysbench_events:
          display:
            description: The number of events sysbench will run
            name: sysbench events
          type:
            type_id: integer
        sysbench_cpumaxprime:
          display:
            description: The upper limit of the number of prime numbers generated
            name: sysbench cpu max primes
          type:
            type_id: integer
        sysbench_runtime:
          display:
            description: The total runtime in seconds for the sysbench tests
            name: sysbench runtime seconds
          type:
            type_id: integer
        elastic_host:
          display:
            description: The host URL for the ElasticSearch service
            name: elasticsearch host url
          type:
            type_id: string
        elastic_username:
          display:
            description: The username for the ElasticSearch service
            name: elasticsearch username
          type:
            type_id: string
        elastic_password:
          display:
            description: The password for the ElasticSearch service
            name: elasticsearch password
          type:
            type_id: string
        elastic_index:
          display:
            description: The index for the ElasticSearch service
            name: elasticsearch index
          type:
            type_id: string
steps:
  pcp:
    plugin: quay.io/arcalot/arcaflow-plugin-pcp:0.2.0
    step: start-pcp
    input:
      pmlogger_interval: !expr $.input.pmlogger_interval
      run_duration: !expr $.input.sysbench_runtime
  sysbench:
    plugin: quay.io/arcalot/arcaflow-plugin-sysbench:0.1.0
    step: sysbenchcpu
    input:
      threads: !expr $.input.sysbench_threads
      events: !expr $.input.sysbench_events
      cpu-max-prime: !expr $.input.sysbench_cpumaxprime
      time: !expr $.input.sysbench_runtime
  metadata:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
    input: {}
  opensearch:
    plugin: quay.io/arcalot/arcaflow-plugin-opensearch:0.1.1
    input:
      url: !expr $.input.elastic_host
      username: !expr $.input.elastic_username
      password: !expr $.input.elastic_password
      index: !expr $.input.elastic_index
      data:
        pcp: !expr $.steps.pcp.outputs.success
        sysbench: !expr $.steps.sysbench.outputs.success
        metadata: !expr $.steps.metadata.outputs.success
outputs:
 success:
   pcp: !expr $.steps.pcp.outputs.success
   sysbench: !expr $.steps.sysbench.outputs.success
   metadata: !expr $.steps.metadata.outputs.success
   opensearch: !expr $.steps.opensearch.outputs.success
 no-indexing:
   pcp: !expr $.steps.pcp.outputs.success
   sysbench: !expr $.steps.sysbench.outputs.success
   metadata: !expr $.steps.metadata.outputs.success
   no-index: !expr $.steps.opensearch.outputs.error
