version: v0.2.0
input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        repeated_inputs:
          type:
            type_id: ref
            id: RepeatedValues
            namespace: $.steps.foreach_loop.execute.inputs.items
        iterations:
          type:
            type_id: list
            items:
              id: SubRootObject
              type_id: ref
              namespace: $.steps.foreach_loop.execute.inputs.items
            
steps:
  foreach_loop:
    # The plugin will be called once for each entry in $.input.iterations.
    kind: foreach
    # It will be passed an object which contains two fields, one containing 
    # the appropriate entry from the iterations list, and one containing 
    # the repeated input data.
    items: !expr 'bindConstants($.input.iterations, $.input.repeated_inputs)'
    workflow: subworkflow.yaml
    parallelism: 1

outputs:
  # We expect to see a list of entries containing the output of each iteration.
  # Each iteration will output the values provided to it for name, ratio, and loop_id.
  success:
    fab_four: !expr $.steps.foreach_loop.outputs.success.data
