input:
  root: RootObject
  objects:
    RootObject:
      id: RootObject
      properties:
        iterations:
          type:
            type_id: list
            items:
              type_id: object
              id: loop_id
              properties:
                loop_id:
                  display:
                    description: ID value for the loop iteration
                    name: Loop ID
                  required: true
                  type:
                    type_id: integer
                nickname:
                  display:
                    description: Just a name
                    name: Name
                  required: true
                  type:
                    type_id: string

steps:
  metadata:
    plugin: quay.io/arcalot/arcaflow-plugin-metadata:0.1.0
    input: {}
  foreach_loop:
    kind: foreach
    items: !expr $.input.iterations
    workflow: sub-workflow.yaml
    parallelism: 1

outputs:
  success:
    metadata: !expr $.steps.metadata.outputs.success
    fab_four: !expr $.steps.foreach_loop.outputs.success.data